# Generated by Django 4.0.7 on 2025-03-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cluster',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
